### ISSUE TITLE
Authorization code grant: "Groups" claim doesn't get refreshed

### ISSUE THREAD

**Issue by jakkab** [kyma-incubator/dex#8]
XSUAA connector do not refresh the `Groups` claim in the authorization code grant scenario. 

Steps to reproduce:
1. follow the authorization code grant flow and decode the JWT token provided by Dex;
2. change user groups and wait for the access token to get refreshed;
3. decode the refreshed access token and compare both `groups` claims.

**Comment by piotrmsc** [comment]
Will be continued in next milestone

**Comment by mmitoraj** [comment]
No DEX in Kyma 2.0.
